- yascheduler/clouds/__init__.py
- yascheduler/clouds/hetzner.py
- yascheduler/clouds/upcloud.py
- yascheduler/data/yascheduler.conf
- yascheduler/scheduler.py
- yascheduler/utils.py
At this time, you cannot specify an SSH username for a specific cloud provider. Some providers assume that the root user is blocked and another user with sudo without a password is used.
This PR allows you to reassign the username. For example:
```ini
;; yascheduler.conf
[remote]
user = root
[clouds]
hetzner_user = yascheduler
```
In this example, the user `yascheduler` will be used for `hetzner` and `root` for the others.
Additionally, `setup_node()` now uses `sudo` if the user is not `root`.
Another slightly off topic change: `apt-get` now waits for the lock file to be released. A couple of times I ran into it, when `apt-get` was already running, and everything crashed.
The code smells a bit, but I tried to keep the changes to a minimum. I tested with hetzner and azure (not released).
> Override SSH username per cloud provider

- pyproject.toml
- requirements.txt
- yascheduler/clouds/__init__.py
- yascheduler/clouds/az.py
- yascheduler/clouds/azure_infra_tmpl.json
- yascheduler/clouds/azure_vm_tmpl.json
The `AbstractCloudAPI` is extended by the `cloud_config_data` property. This is a generic `cloud-config` that can be extended for each provider.
New internal methods have been added to `AbstractCloudAPI` to wait for SSH command execution, with repeating when an exception occurs. This helps to wait for SSH service activation and `cloud-init` (or something else) completion when creating a node.
`AbstractCloudAPI` implemented for `Azure` as `AzureAPI` class.
Azure is a little different: it requires the creation of many objects to allocate a single node. Then, de-allocation of a node also requires removing many objects. `Deployment` objects are used to create a node. One to create common objects (`Network Security Group`, `Virtual Network`, `Subnet`) and one to create node-specific objects …
> Azure cloud provider implementation

- README.md
- yascheduler/__init__.py
Currently, file paths to config/log/pid are hard-coded to the system paths. So, a user without root rights can't run client or server. This PR adds the ability to override these paths with environment variables.
The default behavior is not changed.
> File paths from env

- yascheduler/clouds/az.py
This reverts commit 48f1de627b12b60b3fb07340a864631286cb62e4.
The renaming idea was bad because the `name` field is used as a key:
https://github.com/tilde-lab/yascheduler/blob/master/yascheduler/clouds/__init__.py#L182
> Revert "fix: wrong name (az->azure)"

- yascheduler/clouds/__init__.py
- yascheduler/clouds/az.py
- yascheduler/clouds/hetzner.py
`cloud-init` support, similar to the `azure` provider. Just pass cloud-config content as "user data". Then wait `cloud-init` to finish.
> feat(hetzner): simple cloud-init support

- yascheduler/clouds/az.py
- yascheduler/clouds/azure_infra_tmpl.json
- yascheduler/clouds/azure_vm_tmpl.json
Close #24 
Look's like some Azure API versions are ephemeral. So, version `v2021-03-01` of network API is [removed](https://github.com/Azure/azure-sdk-for-python/commit/e7ae4e0535093479e0964a9330809edb2ff20c40) between minor `19.x.x` versions of the `azure-mgmt-network` package.
Now I only use the versions mentioned in the [reference](https://docs.microsoft.com/en-us/python/api/overview/azure/?view=azure-python).
> fix: azure api versions

- requirements.txt
- yascheduler/__init__.py
- yascheduler/background_worker.py
- yascheduler/clouds/abstract_cloud_api.py
- yascheduler/clouds/cloud_api_manager.py
- yascheduler/clouds/workers.py
- yascheduler/scheduler.py
- yascheduler/time.py
- yascheduler/utils.py
- yascheduler/variables.py
- yascheduler/webhook_worker.py
New dependency - `requests`. Actually, already present because of `azure` libraries.
Implemented threaded webhooks support:
`Yascheduler` starts background `WebhookWorker` threads. Every time the task status is updated On every task status updated (become running or done), it sends task status and metadata to the `WebhookWorker` threads.
If task have a `webhook_url` property in metadata, `WebhookWorker` make a `POST` request to the url `webhook_url` with payload `{ status: int }`.
Less notable changes:
- Generalized `BackgroundWorker` for all workers: `WebhookWorker`, `AllocationWorker`, `DeallocationWorker`.
- Typing fixes.
- Sleep until `current loop step start time + SLEEP_INTERVAL` instead of `current loop step end time + SLEEP_INTERVAL` for main daemon loop and all threads loops.
- …
> Feature: Webhooks

- yascheduler/scheduler.py
Fix this:
```sh
❯ yasetnode 127.0.0.1~4
ERROR:Yascheduler:Host root@127.0.0.1 is unreachable due to: Only %s and %% are supported in the query.
Failed to add host to yascheduler: 127.0.0.1
```
> fix: sql query typo

- yascheduler/scheduler.py
Fix this type of error:
```sh
ERROR:Yascheduler:Host root@127.0.0.1 is unreachable due to: {'S': 'ERROR', 'V': 'ERROR', 'C': '08P01', 'M': 'bind message supplies 9 parameters, but prepared statement "" requires 1', 'F': 'postgres.c', 'L': '1672', 'R': 'exec_bind_message'}
Failed to add host to yascheduler: 127.0.0.1
```
:suspect:
> fix: sql typos again

- requirements.txt
- yascheduler/clouds/abstract_cloud_api.py
- yascheduler/clouds/cloud_api_manager.py
- yascheduler/clouds/hetzner.py
- yascheduler/clouds/upcloud.py
- yascheduler/clouds/workers.py
- yascheduler/data/yascheduler.conf
- yascheduler/engine.py
- yascheduler/scheduler.py
- yascheduler/ssh.py
- yascheduler/utils.py
Introducing the use of Plumbum DSL for shell operations instead of the raw `fabric` commands. `paramiko` is used under the hood as before.
Rudimentary multi-key support: Try to connect using every single key in `keys_dir` instead of just one.
Always run engine's spawn command in background `nohup`ped subschell, so construction `nohup sh -c " ... " &` is not required. Also, run engine's spawn in task's data directory.
Abandon `check` and `run_marker` configuration options (`[engine.*]` sections).
Introduce `check_pname` optional option - process name of running engine.
Introduce `check_cmd` and `check_cmd_code` optional options - shell command that returns `check_cmd` code when engine is running.
At least `check_pname` or `check_cmd` must be set.
Try to always use `Path` (`pathlib`) or …
> Plumbum DSL for shell operations

- yascheduler/scheduler.py
- yascheduler/utils.py
```
usage: yascheduler [-h] [-l {CRITICAL,ERROR,WARNING,INFO,DEBUG,NOTSET}]
Start yascheduler daemon
options:
-h, --help            show this help message and exit
-l {CRITICAL,ERROR,WARNING,INFO,DEBUG,NOTSET}, --log-level {CRITICAL,ERROR,WARNING,INFO,DEBUG,NOTSET}
set log level
```
> Allow to set logging level as command line argument

- yascheduler/scheduler.py
Suddenly, `pathlib` can't do `relative_to` with all path is absolute 🤔 
Anyway, it's useless now, because `task_dir` is already absolute.
> fix: upload task when remote path is absolute

- yascheduler/clouds/cloud_api_manager.py
- yascheduler/scheduler.py
Fix case when allocate more nodes than tasks. Like 5 nodes for 3 tasks.
Details:
Mark task is done (in cloud api manager meaning) not when node is allocated by when task is really allocated to any node.
> fix: greedy allocation

- yascheduler/config/engine.py
Run on any node if no platforms.
> Remote `engine.platforms` default value

- yascheduler/clouds/cloud_api.py
Engines without platforms are skipped in cloud init config. That shouldn't affect node setup because packages are installed later.
> fix: cloud init pkgs when engine without platform

- yascheduler/clouds/cloud_api.py
- yascheduler/remote_machine/linux_methods.py
- yascheduler/remote_machine/windows_methods.py
Example:
```
ERROR:yascheduler.Scheduler.CloudAPIManager.hetzner:Setup node 135.181.207.148 failed: command 'apt-get -o DPkg::Lock::Timeout=600 -y openmpi-bin wget' failed with exit code 100; stderr: E: Invalid operation openmpi-bin
WARNING:yascheduler.Scheduler.CloudAPIManager.hetzner:Setup node 135.181.207.148 failed - deallocate
INFO:yascheduler.Scheduler.CloudAPIManager.hetzner:DELETED 135.181.207.148
ERROR:yascheduler.Scheduler.CloudAPIManager:Can't allocate node: Setup node error: Process exited with non-zero exit status 100
```
> Fail loud when node setup is failed

- yascheduler/remote_machine/protocol.py
- yascheduler/scheduler.py
On task results download retry only on non-fatal errors. Don't fail on all downloads on error. Collect all errors from all downloads.
> Task result download

- yascheduler/remote_machine/protocol.py
There is no `asyncio.exceptions` module in python3.7. So, `setup.py` is silently fail on `pip install ....`
Close #86
> fix: python3.7 incompatibility

- yascheduler/clouds/cloud_api.py
- yascheduler/clouds/cloud_api_manager.py
- yascheduler/clouds/protocols.py
- yascheduler/scheduler.py
Fix `RemoteMachine`'s `engines_dir` is not set when cloud node is allocated.
> fix: remote config omitted on cloud node allocation

- yascheduler/remote_machine/protocol.py
- yascheduler/remote_machine/remote_machine.py
- yascheduler/scheduler.py
Remove useless check that prevent run machine occupancy checks and leads to premature end of task.
Change machine's "busy" state to ternary: busy, free, unknown. If state is unknown and task is assigned to the machine, then run occupancy check before results download. This allows to survive daemon restarts.
> Fix machine occupancy

- setup.py
There is python bug https://github.com/python/cpython/issues/86813 that leads `setup.py` to fail on some 3.9 and 3.10 versions:
```
Exception ignored in atexit callback: <function CustomInstall.run.<locals>._post_install at 0x7fc2343544c0>
Traceback (most recent call last):
File "/code/setup.py", line 26, in _post_install
from yascheduler.variables import CONFIG_FILE
File "/code/yascheduler/__init__.py", line 2, in <module>
from .client import Yascheduler
File "/code/yascheduler/client.py", line 11, in <module>
from .db import DB, TaskModel, TaskStatus
File "/code/yascheduler/db.py", line 6, in <module>
from concurrent.futures import ThreadPoolExecutor
File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
File "/usr/local/lib/python3.10/concurrent/futures/__init__.py", line …
```
> fix: workaround python bug in setup.py

- .flake8
- .github/workflows/linter.yml
- .github/workflows/pr.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
- .pre-commit-config.yaml
- LICENSE
- pyproject.toml
- yascheduler/aiida_plugin.py
- yascheduler/client.py
- yascheduler/clouds/adapters.py
- yascheduler/clouds/hetzner.py
- yascheduler/config/local.py
- yascheduler/remote_machine/checks.py
- yascheduler/remote_machine/remote_machine.py
- yascheduler/scheduler.py
- yascheduler/utils.py
Setup linters again. Drop `pre-commit` from actions for simplicity.
Apply some fixes to code to make linters happy.
Add CHANGELOG.md placeholder.
Setup release automation: auto version bump, changelog update, draft release, publish to pypi.
> Release automation

- examples/submit_topas_input.py
- yascheduler/db.py
- yascheduler/scheduler.py
sort tasks in `yastatus` outputs for more convenient comparison
> feat: stable tasks ordering + minor polishing

- README.md
- yascheduler/config/cloud.py
Fix for yascheduler error: "ERROR:yascheduler.Scheduler.CloudAPIManager:Can't allocate node: Create node error: image 'debian-10' not found" 
debian-11 work just fine
> Change default hetzner OS to debian-11

- examples/submit_any_engine_input.py
- yascheduler/config/utils.py
- yascheduler/db.py
- yascheduler/remote_machine/checks.py
- yascheduler/utils.py
Fix two small bugs in OS detection code:
Unable to get an OS release if the login shell is not POSIX-compliant (`fish`, for example).
Inaccurate handling of tuples leads to an exception and endless spamming of the faulty node (but now I know that `asyncssh` can easily handle 10000 idle connections).
> Fix shell stuff

- .github/workflows/release.yml
Current publishing procedure is broken because of "User 'tilde' does not have two-factor authentication enabled." Therefore, it should be enabled.
In addition, the current approach is to configure Trusted Publisher on the PyPi side:
> Warning: A new Trusted Publisher for the currently running publishing workflow can be created by accessing the following link(s) while logged-in as an owner of the package(s):
> - https://pypi.org/manage/project/yascheduler/settings/publishing/?provider=github&owner=tilde-lab&repository=yascheduler&workflow_filename=release.yml
This PR setup Action as in the documentation https://docs.pypi.org/trusted-publishers/using-a-publisher/
> Trying to fix pypi publishing

- .github/workflows/linter.yml
- .github/workflows/pr.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
- examples/submit_any_engine_input.py
- examples/submit_pcrystal_input.py
- examples/submit_topas_input.py
- pyproject.toml
- yascheduler/__init__.py
- yascheduler/client.py
- yascheduler/clouds/cloud_api.py
- yascheduler/clouds/protocols.py
- yascheduler/config/engine.py
- yascheduler/daemon_sysv.py
- yascheduler/remote_machine/adapters.py
- yascheduler/remote_machine/remote_machine.py
- yascheduler/remote_machine/windows_methods.py
- yascheduler/utils.py
This fixes the asyncio error: `RuntimeError: asyncio.run() cannot be called from a running event loop`
This situation occurs when someone does something stupid. For example, runs synchronous code in asynchronous code, which runs asynchronous code from yascheduler through synchronous code.
For example, when a WSGI netius server runs a synchronous flask app that tries to add a task to the yascheduler via a synchronous wrapper.
The point of the fix is to make a neater wrapper that runs asynchronous code in a thread pool. Also, asynchronous methods are made available for use. These are used in cli utils.
Other changes to fix CI:
+ apply formatting changes (black and isort)
+ fix some pylint errors
+ bump minimal python version
+ bump GH actions versions
> Fix nested async loop

- README.md
- yascheduler/clouds/hetzner.py
- yascheduler/config/cloud.py
The location can be specified in the configuration file. If the location is specified, the server will be created only in that location.
> Add ability to set server location for Hetzner cloud

- CLOUD.md
- examples/own-vm-images/README.md
- examples/own-vm-images/clean-apt-files.sh
- examples/own-vm-images/clean-logs.sh
- examples/own-vm-images/clean-root.sh
- examples/own-vm-images/docker-debian-12-fleur.pkr.hcl
- examples/own-vm-images/flush-disk.sh
- examples/own-vm-images/hcloud-debian-12-fleur.pkr.hcl
- examples/own-vm-images/install-fleur.sh
- examples/own-vm-images/reset-cloud-init.sh
- examples/own-vm-images/reset-ssh-host-keys.sh
- examples/submit_fleur_input.py
An example is added of how to build your own OS image with the right engines in a relatively simple way, so that you don't have to spend time building each time you create a node. This prevents `yascheduler` from turning into a configuration manager, which it is not.
The FLUER engine building in the Hetzner Cloud is used as an example. However, it is not difficult to build an image for another cloud. You'll have to use a different packer configuration, but the engine build scripts shouldn't change.
Also added an example of how to configure yascheduler to use its OS image and the FLEUR engine. Added an example of how to submit a job for the FLEUR engine.
> Bring your own VM image example
