- setup.py
The list of dependencies in `setup.py` is synchronized with `requirements.txt`.
> Update deps in setup file

- yascheduler/data/yascheduler.conf
> Disable all clouds by default

- .github/workflows/black.yml
- examples/submit_dummy_input.py
- examples/submit_pcrystal_input.py
- pyproject.toml
- setup.cfg
- setup.py
- yascheduler/__init__.py
- yascheduler/aiida_plugin.py
- yascheduler/clouds/abstract_cloud_api.py
- yascheduler/clouds/az.py
- yascheduler/clouds/cloud_api_manager.py
- yascheduler/clouds/hetzner.py
- yascheduler/clouds/upcloud.py
- yascheduler/clouds/workers.py
- yascheduler/daemon_systemd.py
- yascheduler/daemon_sysv.py
- yascheduler/engine.py
- yascheduler/scheduler.py
- yascheduler/utils.py
- yascheduler/variables.py
- yascheduler/webhook_worker.py
Reformat with `black` + simple github action.
> `black` experiment

- README.md
- yascheduler/data/yascheduler.conf
- yascheduler/engine.py
Add config file reference.
Check `spawn` command for unknown template placeholders.
> Config file reference

- yascheduler/scheduler.py
Run `mpi` only if `mpi` is available.
> fix: not found mpi command

- yascheduler/clouds/hetzner.py
I got confused about the data types and broke the reuse of the existing SSH keys for Hetzner provider.
> Hetzner SSH Keys

- yascheduler/aiida_plugin.py
- yascheduler/utils.py
This is to introduce an intersection between [AiiDA plugins](https://aiidateam.github.io/aiida-registry) and [yascheduler engines](https://github.com/tilde-lab/yascheduler/blob/c3ede98ef9c0dff7fe75503155addc4d6f432d67/yascheduler/data/yascheduler.conf#L22-L53), which will grow with time.
> Generalize AiiDA integration w.r.t. supported engines

- yascheduler/clouds/cloud_api.py
- yascheduler/remote_machine/checks.py
- yascheduler/remote_machine/remote_machine.py
> Style fixes

- yascheduler/aiida_plugin.py
- yascheduler/scheduler.py
Those were marked as 2 and 3 in our chat :+1:
> Fix two found bugs

- yascheduler/db.py
- yascheduler/utils.py
Skip automigration on db init.
> fix: db init

- yascheduler/scheduler.py
Fix task status in webhook.
Add logging for bad response codes:
```
INFO:yascheduler.Scheduler:Executing webhook to https://webhook.site/sdfsdf/d0a292eb-7ce9-436b-b1a3-f0fa4546ada0?Key=123123
WARNING:yascheduler.Scheduler:Webhook for task_id=6985 bad response: 404 Not Found
DEBUG:yascheduler.Scheduler:Webhook for task_id=6985 response: <!DOCTYPE html>
<html lang="en">
....
```
> fix: webhook status + error logging

- yascheduler/config/cloud.py
I forgot to adjust validator for max_nodes for Hetzner :(
> fix: max_nodes one more time

- yascheduler/clouds/cloud_api.py
- yascheduler/clouds/cloud_api_manager.py
Fix: remove temporary node record in db if node allocation failed
Fix: Remove allocated node if setup is failed
> Recovery on failed node setup

- yascheduler/clouds/cloud_api.py
Do not create multiple keys because of multiple allocation request. Generate on and reuse.
> Synchronize ssh key generation

- .pylintrc
- yascheduler/client.py
- yascheduler/clouds/adapters.py
- yascheduler/clouds/az.py
- yascheduler/clouds/cloud_api.py
- yascheduler/clouds/cloud_api_manager.py
- yascheduler/clouds/hetzner.py
- yascheduler/clouds/protocols.py
- yascheduler/clouds/upcloud.py
- yascheduler/daemon_sysv.py
- yascheduler/db.py
- yascheduler/queue.py
- yascheduler/scheduler.py
- yascheduler/time.py
- yascheduler/utils.py
- yascheduler/variables.py
Fixing code smell. Not completed, but closer.
> More pylinting

- yascheduler/client.py
- yascheduler/utils.py
@knopki is this good enough or can be better?
> Return only the ID instead of the whole task dict

- yascheduler/clouds/adapters.py
- yascheduler/clouds/az.py
- yascheduler/clouds/cloud_api.py
- yascheduler/clouds/hetzner.py
- yascheduler/clouds/protocols.py
- yascheduler/clouds/upcloud.py
- yascheduler/clouds/utils.py
- yascheduler/config/local.py
- yascheduler/remote_machine/protocol.py
- yascheduler/remote_machine/remote_machine.py
- yascheduler/scheduler.py
Fix black magic with ssh connection options.
Feature: per-cloud initial ssh connection timeout.
> Fix ssh connection issues

- WINDOWS.md
- yascheduler/scheduler.py
Fix for windows and short documentation on how to prepare node.
> Windows fix + docs

- yascheduler/clouds/cloud_api.py
- yascheduler/clouds/cloud_api_manager.py
- yascheduler/clouds/protocols.py
Potential fix of "got future attached to a different loop" on node allocation. Should be tested.
> fix: different event loop on node allocation

- yascheduler/remote_machine/adapters.py
- yascheduler/remote_machine/checks.py
- yascheduler/remote_machine/remote_machine.py
> Support ancient windows versions

- .pre-commit-config.yaml
- CHANGELOG.md
- pyproject.toml
- yascheduler/__init__.py
Fix configuration and add initial CHANGELOG
> Release automation

- yascheduler/remote_machine/adapters.py
- yascheduler/remote_machine/checks.py
- yascheduler/remote_machine/remote_machine.py
Add Debian 12 and some future OS releases. So you don't have to remember it for longer.
> Support more OS checks

- .gitignore
> Add tmp commitizen changelog to .gitignore

- yascheduler/config/cloud.py
- yascheduler/config/db.py
- yascheduler/config/engine.py
- yascheduler/config/local.py
- yascheduler/config/remote.py
- yascheduler/config/utils.py
- yascheduler/scheduler.py
- yascheduler/utils.py
Also, change default logging level to WARN and enable capturing of warnings.
> Print warnings when there are unknown keys in config

- yascheduler/remote_machine/remote_machine.py
> Allow using from Python 3.8-3.9

- pyproject.toml
- yascheduler/__init__.py
Trying to fix "version set in the two places"
> The only one version number in the one place
